required-players: 2
max-players: 8
countdown-seconds: 30
error-prefix: '&f[&cError&f]&r'
success-prefix: '&f[&Success&f]&r'
lobby-spawn:
  world: 'world'
  x: 0
  y: 64
  z: 0
  yaw: -180
  pitch: 0
arenas:
  0:
    world: 'minigame'
    x: 0
    y: 64
    z: 0
    yaw: 180
    pitch: 0