name: TLI-Minigame-Engine
version: '1.0-SNAPSHOT'
main: mc.tli.minigame_engine.TliMinigameEngine
api-version: '1.20'
load: POSTWORLD
authors: [ Royboot ]
commands:
  moderationban:
    description: used to ban people in the middel of live minigames
    usage: /miniban
  game:
    description: used to start a minigame
    usage: /game
  test:
    description: used to test the plugin
    usage: /test
  create:
    description: Create a simple void world
    usage: /create <world_name>
    permission: tli.create.world
    permission-message: You don't have permission to create worlds!


